### PR TITLE
Added a new tipspacer shape: Pointy.

### PR DESCRIPTION
**Pull request by bill622**
This kind of core shape was used by K2 in early 90's and will facilitate cutting the wood core and the tip filler for a proper match.

In StatPanel (or Board properties), nose height and tail height values are now displayed

### CODE REVIEW

**Comment by mikemag** [comment]
Hey man, I'm so sorry for not getting back to you sooner! I never got a notification about this pull request, and it honestly never occurred to me that anyone else was working on it! :) I will take a look this weekend for you.

**Comment by mikemag** [comment]
I skimmed thru this tonight and it looks pretty reasonable to me. I don't know the source of SnoCAD-X very well yet, and I'm fuzzy on a lot of the UI stuff, so what I'll do is pull it down this weekend and give it a try myself. Assuming it works reasonably I see no reason not to merge it in. @danielgraf, if you get to that before me feel free to merge it in!

**Comment by mikemag** [comment]
I pulled this down this evening and played with it. Works just fine. Merging.

**Comment by bill622** [comment]
Thanks! I'll keep working with "forking" I prefer to stay as a "non-direct" contributor, this way, my code is reviewed.

**Pull request merged**
